### ISSUE TITLE
variable fonts: require old macOS name IDs

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#1590]
- [ ] @twardoch says in http://typedrawers.com/discussion/comment/30510/#Comment_30510

> Predefined instances in variable fonts on macOS Sierra and older need their names in the PID.EID=1.0 slots, because the code that reads GX varations in macOS is old. 

We should have a check for that.

**Comment by anthrotype** [comment]
> Predefined instances in variable fonts on macOS Sierra and older need their names in the PID.EID=1.0 slots, because the code that reads GX varations in macOS is old.
>> We should have a check for that.

Should we care? Variable fonts (as in OpenType 1.8, not GX) are not supported on macOS Sierra and older (not officially anyway), and I've been told (though I still haven't tried) that in High Sierra the old GX limitation on PID=1 is gone.

**Comment by felipesanches** [comment]
Moved request of "required STAT table" check to https://github.com/googlefonts/fontbakery/issues/1671

**Comment by felipesanches** [comment]
Are we expecting entries with MacOS plat-ID for only specific name IDs? Which ones?

**Comment by twardoch** [comment]
I think the fact that a really large number of older Mac OS X systems can use predefined instances in TrueType-flavored OpenType variable fonts precisely because they're backwards-compatible with TrueType GX fonts, is very useful. Shipping PID=1 names is similar to shipping the TrueType kern table in OpenType fonts — for a few years after introduction of OpenType, it was a good idea. Maybe it isn't anymore now, but I think since shipping PID=1 names is "cheap" in space and engineering, it's worth it.

**Comment by felipesanches** [comment]
I'm still not convinced that this is really necessary.

**Comment by felipesanches** [comment]
And, if so, then which specific name entries we're talking about?

**Comment by simoncozens** [comment]
I'm pretty sure this is dead now. We don't really want to add name table entries to support broken versions of obsolete operating systems...
