### ISSUE TITLE
Allow projects to expect non-PASS results

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#2558]
## Observed behaviour

Users use the FontBakery report as a check list of things to do. 

Users get WARN or even FAIL results, but may have a special exception from their distributor to ignore that result.

## Expected behaviour

Therefore they want to have a 'profile profile' (lol) which allows them to say they expect a non-PASS result on a given check, and see an PASS-class EXCEPTION result instead.

**Comment by felipesanches** [comment]
seems similar to #2356

**Comment by felipesanches** [comment]
@graphicore said in a private chat that he's interested in working on this one

**Comment by felipesanches** [comment]
I think that all log messages should have a code such as this:

<img width="537" alt="Captura de Tela 2019-06-27 às 16 30 23" src="https://user-images.githubusercontent.com/213676/60294946-e43c9e00-98f8-11e9-87f8-605d1368d828.png">


Then we can have a mechanism for users to reference specific failures and bypass them. If checks simply emit a FAIL without a log-message keyword, then user settings may be ambiguous.

Here's a few ways this could back-fire if keywords are not used:

## usage scenario 1

* A check emits a FAIL without a keyword.
* A user configures her own font project to bypass this FAIL and interpret it as a PASS
* FontBakery is updated and now the check emits 2 different kinds of FAILs, but still without respective keywords.
* As a result, the user will be unknowingly hiding the new kind of FAIL

This is a bad outcome!

## usage scenario 2

* A check emits a FAIL with a keyword "foo".
* A user configures her own font project to bypass this (FAIL, "foo") and interpret it as a PASS
* FontBakery is updated and the check implementation changed enough so that we decided to rename the FAIL to make it clear that it now reports a different kind of problem. We call it (FAIL, "bar") now.
* The user's bypassing is now not blocking the new kind of problem.

This is a good thing!

**Comment by felipesanches** [comment]
If the setup is only possible for log messages that have a keyword, then these bad outcomes become impossible.

We would have to gradually add keywords to all log-messages then, in order to enable users to bypass them unambiguously.

**Comment by felipesanches** [comment]
I've been working on this one and even though I still do not have implemented the logic for performing the bypassing, I am adding log-message IDs to all messages in the gfonts profile.
