### ISSUE TITLE
Add support for OpenType font collection testing

### ISSUE THREAD

**Issue by chrissimpkins** [fonttools/fontbakery#2595]
Associated IR: #2593 

Many CJK typefaces are released in the `*.ttc` or `*.otc` format due to space savings that come from OT table sharing in this release format.  It would be helpful to be able to enter an OpenType font collection as an argument to the fontbakery executable and have profile checks performed on each font that is included in the font collection.

`fontTools.ttLib.TTFont` objects can be instantiated for each font in the collection with the `fontNumber` argument and an integer index definition:

https://github.com/fonttools/fonttools/blob/1dcb3c2bde86e9977bb384046e594e35ecd18796/Lib/fontTools/ttLib/ttFont.py#L21-L25

**Comment by felipesanches** [comment]
Sounds great! I will look into it more carefully. Thanks for the tip!

**Comment by anthrotype** [comment]
You can use fontTools.ttLib.ttCollection.TTCollection class to load them all at once, then you can iterate over them like a list of TTFonts

**Comment by davelab6** [comment]
@felipesanches @simoncozens I have an internal project with TTC requirements so I'd like to see if we can do this in Feb :)

**Comment by simoncozens** [comment]
I feel like this will be challenging with the current architecture, but this could be due to my lack of understanding.

I can see how - in the "normal" case, each *individual* input file in a list can get converted through a "derived iterable" to multiple TTFont objects, but I have no idea how to "explode" a *single* file into *multiple* iterables. I have especially no idea how, if we have a check which takes a single `ttFont` object, a single file (in this case, a TTC) can be used to drive multiple instances of the same check.

Maybe @graphicore can shed any light on it?
