### ISSUE TITLE
FontBakery does not accept the © copyright symbol and other non-ASCII in copyright notices

### ISSUE THREAD

**Issue by tphinney** [fonttools/fontbakery#2854]
## Observed behaviour

I was surprised that FontBakery rejects non-ASCII characters in the name table, especially the © copyright symbol, which is a natural in the copyright notice. Certainly a very large number of fonts in the world use this.

Additionally, sometimes project authors or even project names themselves might contain accented characters and other non-ASCII. (Perhaps even non-Latin, but even if we stick to basic Mac/Windows characters....)

The single example of a copyright notice in the current OpenType spec uses a copyright symbol.

> The following are examples of how these strings might be defined, based on Times New Roman Bold:
> 
> 0. The copyright string from the font vendor. _© Copyright the Monotype Corporation plc, 1990_

In my case, it was:

> FontBakery complaint
> * �[1;91;107mFAIL�[0m: Bad string at [nameID 0, 'mac_roman']: 'b'Copyright © 2019 Font Detective LLC.'' [code: bad-string]
> * �[1;91;107mFAIL�[0m: Bad string at [nameID 0, 'utf_16_be']: 'b'Copyright © 2019 Font Detective LLC.'' [code: bad-string]
> * �[1;91;107mFAIL�[0m: There are 2 strings containing non-ASCII characters in the ASCII-only NAME table entries. [code: non-ascii-strings]

## Expected behaviour

Accept the copyright symbol '©' without error.

## Resources and exact process needed to replicate

Run FontBakery on most any major vendor’s fonts. I found Apple Color Emoji and Verdana both have this issue, for example.

See also: https://github.com/tphinney/science-gothic/issues/238

**Comment by m4rc1e** [comment]
Since the family is ofl, we expect the copyright to follow, https://github.com/googlefonts/gf-docs/tree/master/Spec#font-copyright

**Comment by davelab6** [comment]
> Accept the copyright symbol '©' without error.

The reason I specified this check is that I want the copyright notice to be the same everywhere, as the OFL requires the notice to be retained, and the CFF table's copyright notice key is ascii only.

> `�[1;91;107mFAIL�[0m: Bad string at [nameID 0, 'mac_roman']: 'b'Copyright © 2019 Font Detective LLC.'' [code: bad-string]`

BTW, I am curious why your copy & paste includes the ansi terminal color code characters? Is that a fontbakery bug?

**Comment by tphinney** [comment]
Just noticed that this seems like a duplicate of #1718

**Comment by tphinney** [comment]
AFAIK Adobe has continuously released OpenType CFF fonts from at least **2000 to very recently**, with the copyright symbol in the name table. Back in the day it was a requirement for every Adobe font.

From Minion Pro from circa 2002, early OpenType releases
    <namerecord nameID="0" platformID="1" platEncID="0" langID="0x0" unicode="True">
      © 2000, 2002 Adobe Systems Incorporated. All Rights Reserved. U.S. Patent Des. 337,604. Other patents pending.

From Minion Variable Concept released around 2018
    <namerecord nameID="293" platformID="1" platEncID="0" langID="0x0" unicode="True">
      MinionConceptRoman-DisplayBold
    </namerecord>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      © 1990-2018 Adobe. All rights reserved.

**Comment by davelab6** [comment]
@tphinney right, the name table supports that character in CFF same as TTF, but **the CFF table** itself has a copyright notice key, and **that** is ascii only.

**Comment by rimas-kudelis** [comment]
@davelab6, please reconsider.

The whole section about Copyright and Trademark Notices has been removed from the CFF specification back in 2000 (see appendix I [here](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5176.CFF.pdf)), but even before that this field was specified as optional and without any strictness (section 18 [here](https://web.archive.org/web/20000823103405/http://www.microsoft.com/typography/OTSPEC/cff.pdf), also [this comment](https://github.com/fonttools/fontbakery/issues/1718#issuecomment-367398623)).

Furthermore, Adobe itself [stopped supporting Type 1 fonts](https://helpx.adobe.com/fonts/kb/postscript-type-1-fonts-end-of-support.html) in their products last year, telling users to switch to OpenType fonts instead. And, as you know, OpenType fonts have a separate unicode-compatible table for storing copyright strings, which (again per comment linked above) has higher priority than the strings in the CFF table.

IMO, requiring font authors to limit themselves to ASCII in 2024 just because there exists a legacy field in one of the OpenType tables with such constraint doesn't make sense. Why not replace this requirement with a check that no copyright string is stored in the CFF table, for example?

**Comment by davelab6** [comment]
> @davelab6, please reconsider.

Thanks for asking. I chatted with folks around this, reconsidered, and now I do agree with you about this.
 
> The whole section about Copyright and Trademark Notices has been removed from the CFF specification back in 2000 (see appendix I [here](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5176.CFF.pdf)), but even before that this field was specified as optional and without any strictness (section 18 [here](https://web.archive.org/web/20000823103405/http://www.microsoft.com/typography/OTSPEC/cff.pdf), also [this comment](https://github.com/fonttools/fontbakery/issues/1718#issuecomment-367398623)).

Sure, but that was known as the case when this was decided before :) 

> Furthermore, Adobe itself [stopped supporting Type 1 fonts](https://helpx.adobe.com/fonts/kb/postscript-type-1-fonts-end-of-support.html) in their products last year, 

Yes, and that is new - and significant.

> telling users to switch to OpenType fonts instead. And, as you know, OpenType fonts have a separate unicode-compatible table for storing copyright strings, which (again per comment linked above) has higher priority than the strings in the CFF table.

Yes. Pure CFF fonts used as such, have a name table, and the CFF copyright string can be zero'd out, and its fine. 

Type-1 conversion is now no longer a valid use-case, and while some conversion to Type-1 still happens "on the fly" for printing, since it is transient I am not fussed about it.

> IMO, requiring font authors to limit themselves to ASCII in 2024 just because there exists a legacy field in one of the OpenType tables with such constraint doesn't make sense. Why not replace this requirement with a check that no copyright string is stored in the CFF table, for example?

I like that suggestion. @felipesanches please do it :)

**Comment by rimas-kudelis** [comment]
Cool! As you can see, after a handful of failed builds I have a working PR ready. :)
