### ISSUE TITLE
Make reports more succinct

### ISSUE THREAD

**Issue by m4rc1e** [fonttools/fontbakery#2915]
I have no problems with verbosity however I don't want a tonne of information in my reports. I echo @chrissimpkins thoughts about including more info about a check in a separate doc.

MS Font Validator does this quite nicely. If your font fails a check, it outputs the failed check id and a hyperlink to a help file.

When a check fails in FB, I'd like it to output the check ID, what value I currently have and what value it should be. I'd then like a hyperlink that would give me the rationale and possible hints on how to fix the issue.

**Comment by m4rc1e** [comment]
As an example, here's the output for the dsig check:

<img width="1392" alt="Screenshot 2020-06-08 at 11 26 30" src="https://user-images.githubusercontent.com/7525512/84020570-ef0e0880-a97a-11ea-9736-6da94c75518d.png">

**Comment by felipesanches** [comment]
while I understand your need, I also do not want to destroy the informative UI that we've built up to now. So maybe we should consider creating a command-line option to let you choose a different, more sucint UI while still making it possible to use the current UI by default (when the optional CLI switch is not passed).

**Comment by m4rc1e** [comment]
I'm sorry but I have to disagree.

The rationales/text we have in place imo is not informative enough and there are no notes on how to fix issues. If we do improve the rationales/text, we'll need a way to hide this information since it will make the reports even longer.

Another big issue is the repetition. If you have a family which has 18 fonts and they all fail the same check, you get the same rationale/help text 18 times. You only really need to see it once.

**Comment by felipesanches** [comment]
What I meant is that we can create the succinct experience you're requesting, but I don't want to remove the current one in order to achieve it.

And additional reasoning is that, since all the data needed is available on its own source code, it would be dumb to force users to always lookup an online reference documentation making fontbakery effectively useless when offline (During an ISP service shortage? Poor network access on a rural area? Working on an airplane? etc).

**Note:** I've somewhat regularly been myself in all 3 situations forcing me to work offline

Having said that, we do indeed have an online reference documentation at https://font-bakery.readthedocs.io/en/latest/ and it would be cool and useful to have an **optional** succinct mode that only gives you the check-id and expects you to lookup the online resource. Would be bad to force this into being mandatory, though.

**Comment by felipesanches** [comment]
Regarding the repetition of rationale text when the same check runs multiple times, I agree that this is inconvenient, but it is a side effect of the check execution ordering. I recall we've introduced mechanisms for changing such ordering, but I think they're far from being intuitive. In general I think we need to perform a major redesign on the way we handle verbosity since we have multiple overlaping concepts that control the output of information and the level of details. Such redesign will almost certainly result in incompatibility with CLI switches, so I'd like to do it all at once prior to a major version bump such as **FB v1.0.0** ;-)

I'd also like to change some other core features such as **-- offtopic alert --** making it possible to invoke checks without having to explicitly state the profile name on the command line. But I digress. This is starting to become offtopic here :-)

**Comment by m4rc1e** [comment]
> What I meant is that we can create the succinct experience you're requesting, but I don't want to remove the current one in order to achieve it.

Checking all [18 static Montserrat fonts](https://github.com/JulietaUla/Montserrat/tree/master/fonts/ttf) or any large family is very painful. However, the github markdown reports are actually pretty good because the results are not presented all at once. We honestly should improve the default experience to make this tool more user friendly.


> force users to always lookup an online reference documentation making fontbakery effectively useless when offline (During an ISP service shortage? Poor network access on a rural area? Working on an airplane? etc).

It doesn't have to live online. We could just include a generated html file in the pypi package. We don't even need to maintain a seperate doc source for this. All info could just reside in the check itself.


I'm not suggesting that my approach is the best one. I just feel we need to do something about this. I'll create a mockup and present this on Friday.

**Comment by felipesanches** [comment]
> I'll create a mockup and present it on Friday.

thanks!

**Comment by m4rc1e** [comment]
Here's a quick proposal

```
Fontbakery Report:
profile:    check-googlefonts:
fonts:      font1.ttf, font2.ttf, ...

>>  Check:  com.google.fonts/check/license/OFL_copyright
    Desc:   Check license file has good copyright string.
    Files:  All fonts
    Detail: First line in license file does not match expected format:
            "apache license"
    Result: FAIL
		
>>  Check:  com.google.fonts/check/dsig
    Desc:   Checking fonts have DSIG tables
    Files:  All fonts
    Detail: DSIG tables not found
    Result: FAIL
		
>>  Check:  com.google.fonts/check/usweightclass
    Desc:   Checking OS/2 usWeightClass.
    Files:  Rokkitt-Thin.otf
    Detail: OS/2 usWeightClass is '100' when it should be '250'
    Result: FAIL
		
>>  Check:  com.google.fonts/check/usweightclass
    Desc:   Checking OS/2 usWeightClass.
    Files:  Rokkitt-ExtraLight.otf
    Detail: OS/2 usWeightClass is '200' when it should be '275'
    Result: FAIL
		
>>  Check:  com.google.fonts/check/name/license
    Desc:   Check copyright namerecords match license file.
    Files:  OFL.txt
    Detail: License file LICENSE.txt exists but font doesn't have NameID 13
    Result: FAIL
		
>>  Check:  com.google.fonts/check/vendor_id
    Desc:   Checking OS/2 achVendID.
    Files:  All fonts
    Detail: "NEWT" not found in https://docs.microsoft.com/en-us/typography/vendors/   
    Result: WARN
		
>>  Check:  com.google.fonts/check/name/license_url
    Desc:   Check copyright namerecords match license file.
    Files:  All fonts
    Detail: Please consider using HTTPS URLs
    Result: WARN
		
>>  Check:  com.google.fonts/check/unitsperem_strict
    Desc:   Checking font upm
    Files:  All fonts
    Detail: Please consider using 2000upm
    Result: WARN
		
>>  Check:  com.google.fonts/check/ligature_carets
    Desc:   Checking font has ligature carets
    Files:  All fonts
    Detail: Fonts lacks caret position values for ligature glyphs in GDEF table.
    Result: WARN
		
>>  Check:  com.google.fonts/check/kerning_for_non_ligated_sequences
    Desc:   Checking fonts have kerning for ligature sequences
    Files:  All fonts
    Detail: GPOS table lacks kerning info for some ligated sequences
    Result: WARN
		
>>  Check:  com.google.fonts/check/ftxvalidator_is_available
    Desc:   Checking system has ftxvalidator installed
    Files:  N/A
    Detail: ftxvalidator not found
    Result: WARN

Summary:
    ERROR: 0
    FAIL: 4
    WARN: 7
    INFO: 6
    SKIP: 90
    PASS: 67

For further information and documentation for each check visit: some/local/file.html

```

Key differences:
- Better formatting
- Revised and shortened output messages
- Fonts/files are grouped by check. This removes the repetition.
- Check results are Fail to Info


The current fontbakery output can be found [here](https://gist.github.com/m4rc1e/07e9b6a73e58f37fb50f1850bfd61499). The original FB report is over 2,000 lines, this report is still wip and is around 80 (probably be closer to 100 once finished)

**Comment by graphicore** [comment]
How about making different reporters? It doesn't have to be one size fits all.

**Comment by m4rc1e** [comment]
I'd personally prefer us to improve the default experience. However, if making such changes is going to break tools which use Fontbakery then I'm happy for it to be a custom reporter.

**Comment by graphicore** [comment]
Everybody wants to achieve a good user experience, but also has a different user perspective in mind. We could have a personal preference in a `~/.fontbakery` file to choose a reporter "style". Of course, one thing would still be the default and everybody would use that. :shrug:

**Comment by felipesanches** [comment]
@m4rc1e here's a nice `--succinct` for you to enable it. :-D
We can later tweak it a bit more. Here's how it looks now:

![Screenshot from 2020-06-09 14-34-24](https://user-images.githubusercontent.com/213676/84182308-93b64600-aa60-11ea-838d-cfdc0df8005a.png)

**Comment by felipesanches** [comment]
we will treat the matter of selecting default behavior in a separate issue (#2734)

**Comment by felipesanches** [comment]
I know that my first implementation of the --succinct mode does not have all features you requested, but we'll be able to reopen the issue if needed later. I'd like to first see you're full mockup next Friday meeting.

Please also consider that "Revised and shortened output messages" would be hard to provide without writing such messages twice on the check implementations, wich would be a burden on our development efforts. And I prefer to have explicit and clear full sentences on the documentation (the check source code) instead of the risk of more ambiguity.

**Comment by m4rc1e** [comment]
I really appreciate it thank you.

> Please also consider that "Revised and shortened output messages" would be hard to provide without writing such messages twice on the check implementations

Agreed. Imo, the pass/warn/fail messages should be more concise. The details should be supplied in the rationales.

**Comment by felipesanches** [comment]
@m4rc1e, `--succinct` is now extremely succinct.

![Screenshot from 2024-01-26 12-40-12](https://github.com/fonttools/fontbakery/assets/213676/5ea2ab3c-c8be-47e4-8fd5-58ebc3e0b041)

**Comment by m4rc1e** [comment]
Personally, I love it. If I need to inspect further, I can just rerun with individual checks.
