### ISSUE TITLE
OpenType small caps and ligature ordering

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#3020]
https://twitter.com/mekkablue/status/1297486769668132865?s=19

> OpenType pro tip: make sure your small cap lookups are defined before your ligature lookups. You’re welcome. 
>
> ![Screenshot_20200823-091044](https://user-images.githubusercontent.com/261579/90979087-91706d80-e520-11ea-9e8b-352f00eea2b0.png)

**Comment by kalapi** [comment]
Hi @felipesanches Can we add the following exceptions:

If the font is monospaced _and_ does not contain `liga` _and/or_ `smcp` we skip this check?

**Comment by driehuis** [comment]
Getting fresh fails as a result of this check on [DINish](https://github.com/playbeing/dinish) with fontbakery 0.12.8.

This check is not relevant to fonts without `smcp` feature, and last I checked, that feature was not mandatory.

Line 1251 of Lib/fontbakery/checks/universal/__init__.py should be SKIP rather than FAIL, IMHO. I'll submit a pull request to that effect.

**Comment by vv-monsalve** [comment]
@felipesanches, as @driehuis says, none of the reported features are mandatory for a font _if_ it doesn't have Small Cps or Ligatures. So, if a font doesn't include either one or both of the features, it should not be a FAIL but SKIP.

You can use this as a [test case](https://github.com/google/fonts/pull/7936#issuecomment-2220492463)
