### ISSUE TITLE
What are the checks that FAIL more frequently on the Google Fonts collection?

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#3280]
**Task:** Run fontbakery on all the family folders in the `google/fonts` repo and tabulate the check-id FAIL (and maybe also WARN) frequencies.

**Comment by RosaWagner** [comment]
This check `⚠ WARN: Is there kerning info for non-ligated sequences?` is systematically ignored for multiple reasons:

1. some ligature or not of letters (example` -->` to create an arrow)
2. in the case of ligature `tt` for example, it can be good to keep the option of not having the letters touching, by deactivating the ligature.
4. ligatures are often ornemental which doesn't necessitate a kerned sequenced from the base pair

Since this check apply only for edge cases and not for common usage, it could be removed entirely, or only for a specific profile of a specific client.

**Comment by simoncozens** [comment]
Here's a spreadsheet: https://docs.google.com/spreadsheets/d/1TycCvPSFjar1Y5l8A4j7L9QN1xuDdMO2Pah1b26nJuE/edit#gid=2146669006
