### ISSUE TITLE
check google-fonts: Fail families which only contain Kana

### ISSUE THREAD

**Issue by m4rc1e** [fonttools/fontbakery#3384]
## Observed behaviour

We pushed a [Japanese family](https://fonts.google.com/?query=Otomanopee&subset=japanese) which only contains Kana. Atm, the GF sample text for Japanese uses all three Japanese writing systems so Kana only fonts will produce tofus.

This check should be deprecated once we implement a Kana only sample text.

**Comment by felipesanches** [comment]
@aaronbell, what do you think?

**Comment by aaronbell** [comment]
The particular issue for Otomanopee is that it contains **some** Kanji but doesn't contain a full Kanji set. So at first glance it appears not to be a kana-only font. 

Rather than checking for kana-only (which Otomanopee would pass) I think that this check should evaluate if the font contains a minimum character set for Japanese Kanji. I'd suggest the JIS1 character set, which contains key characters for widespread use, and more frequent characters. It also contains the Kanji included in the GF string. 

Interestingly, I'd actually suggest that once GF is able to display Kana-only fonts without issue, it would make sense to preserve this check and call out if the font contains some Kanji but doesn't contain the full JIS1 character set to encourage designers to fill out a minimum character set not unlike the requirement around the Google Font's Core glyphset.

**Comment by simoncozens** [comment]
We fixed this on the GF side - kana-only fonts are now allowed, and have their own sample texts.
