### ISSUE TITLE
[Checking with fontTools.ttx] Name ID 256 not required for statics

### ISSUE THREAD

**Issue by emmamarichal** [fonttools/fontbakery#3671]
## Observed behaviour

I have this fail when I run fontbakery on a static font: 

</summary><div><details><summary>🔥 <b>FAIL:</b> Checking with fontTools.ttx (<a href="https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/ttx-roundtrip">com.google.fonts/check/ttx-roundtrip</a>)</summary><div>

* 🔥 **FAIL** name id 256 missing from name table
* ℹ **INFO** While converting TTF into an XML file, ttx emited the messages listed below.
</div></details>

## Expected behaviour

Maybe we could remove this check for fonts that are not variable?

## Resources and exact process needed to replicate

Repo: https://github.com/emmamarichal/Joan
The file that I checked: https://github.com/emmamarichal/Joan/tree/main/fonts/ttf

**Comment by RosaWagner** [comment]
Indeed, this correspond to name ID linked to STAT and FVAR table, which are variable font tables. This check shouldn't perform on static fonts.

**Comment by felipesanches** [comment]
I suspect this means a bug in `ttx`.

If that's the case, then ttx should be fixed while ttx round-tripping should still be ensured by running the check on all fonts regardless of them being statics or VFs.

**Comment by felipesanches** [comment]
The `ttf-roundtrip` check was originally proposed by @davelab6 at #1763

**Comment by m4rc1e** [comment]
NameID 256 isn't just for VF stuff. It's the first available nameID which folks can use themselves for fvars, stats, stylistic set names etc. 

It also isn't a bug in TTX. TTX is reporting that this nameID is missing from the font so the font is broken.

I've just seen the same error in Pacifico, https://github.com/google/fonts/pull/7104. This family is getting flagged because the stylistic sets have `UINameID`s set to 256, 257 etc when they don't exist.

<img width="705" alt="Screenshot 2024-01-09 at 10 33 17" src="https://github.com/fonttools/fontbakery/assets/7525512/e6fb7126-6df2-4c9b-9ef2-8be5c9d8c7b1">

I reckon this may be happening inside the glyphs file here.

<img width="1260" alt="Screenshot 2024-01-09 at 10 40 23" src="https://github.com/fonttools/fontbakery/assets/7525512/e2a2d43b-99d2-46d7-9f41-a48706530487">
*Empty Feature Name field may be causing this*

Imo Glyphs should allow this field to be empty since stylistic sets shouldn't need names. If this is the case, I'll open an issue in GlyphsApp.

cc @emmamarichal

**Comment by davelab6** [comment]
Nice @m4rc1e :) Now that the glyphsLib PR is merged, what's the next step for FB?

**Comment by simoncozens** [comment]
There wasn't a FB bug here. It was genuinely reporting a brokenness in the font. Next step is to close this issue? :-)

**Comment by felipesanches** [comment]
yes, thanks @simoncozens
