### ISSUE TITLE
Don’t suggest copying OFL from arbitrary GitHub repositories

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fontbakery#3734]
## Observed behaviour

`com.google.fonts/check/license/OFL_body_text` has the following text:
> FAIL The OFL.txt body text is incorrect. Please use https://github.com/googlefonts/Unified-Font-Repository/blob/main/OFL.txt as a template. You should only modify the first line. [code:incorrect-ofl-body-text]

I find this very bogus, since as far I’m concerned https://github.com/googlefonts/Unified-Font-Repository is some random GitHub repository.

## Expected behaviour

Link to the official OFL page https://scripts.sil.org/OFL

**Comment by RosaWagner** [comment]
This is GF requirements, all fonts must have the exact same OFL.txt layout so we are sure the license has not been modified. This repo has been made for that purpose (now called "googlefonts-project-template").

**Comment by khaledhosny** [comment]
Still, I don’t see how I, as a designer, should trust this version of the OFL.txt over the official one. If this OFL.txt is the same as the official one, then you should point to the official one, if it is not I don’t think you can do that since OFL text is copyright of SIL International.

**Comment by felipesanches** [comment]
@khaledhosny, I agree.

Since your point is a bit pedantic, I'll follow suit: the "googlefonts-project-template" repo is not really "random", the correct term would actually be "arbitrary" ;-)

But, yeah, I agree with you that we should suggest the official OFL text. And we should also make sure FontBakery checks against that specific license text (in other words, make sure our copy did not diverge from the original, official text).

**Comment by yanone** [comment]
We know that the URL is not random because we provided the content, and it's technically trivial to compare the contents to the original text provided by SIL for whoever is suspicious. However, SIL doesn't provide a plain text file to copy/paste the contents from for our fontbakery check to compare against successfully. Pointing to https://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web will introduce more problems than it solves, as it's arguably not a plain text file.
https://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=OFL_plaintext&filename=OFL.txt will download a plain text file rather than showing it inline in the browser. Okay, whatever, fine. But it still contains the arbitrary copyright header that needs to be adjusted to out needs and users _will_ fail at this.

**Comment by khaledhosny** [comment]
The copy in that googlefonts repository have at least one change compared to the official version (replacing http with https in the OFL URL), and while this is probably OK, it shows why I’m reluctant to use an unofficial copy of the license as I wouldn’t know what changes it might have introduced without comparing the two, so it is more not less work for me.

**Comment by felipesanches** [comment]
I'm sorry, but this seems pointless.

**Comment by khaledhosny** [comment]
I don’t see why we can’t tell people to get the license from its official home?
