### ISSUE TITLE
[com.google.fonts/check/transformed_components] Should be conditional on the use of hinting

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fontbakery#3738]
## Observed behaviour

Any font using transformed components gets an `com.google.fonts/check/transformed_components` error, whether or not it is affected by the issue. The rationale talks about issues with hinting, but the code errors even if the font has no hinting.

## Expected behaviour

No error when transformed components are used if the font is not autohinted with ttfautohint.

## Resources and exact process needed to replicate

Decomposing transformed components can considerably affect file size, in one of my fonts it causes ~13% increase, so I’m not going to do this for an issue that does not actually affect the font.

**Comment by RosaWagner** [comment]
Without hinting, the only type of annoying transformed component would be the mirroring one, since it reverses contour direction. Can be a bother in some hard-to-predict cases (depending on how the components is used and the rasteriser I guess, we need test-cases), interpolation (I think there is an issue from @arrowtype somewhere about it) and overlapping components in VF. 

The other thing is that GF API will instanciate static fonts from the VF, and I don't know if the transformed components will be decomposed if they are not already in the VF. So we need to check if it's the case or not, and if these static fonts will have ttfautohint applied or not. 

So there are few stuff to investigate to update the rational accordingly.

**Comment by yanone** [comment]
Btw, if contour direction is indeed an issue, the check could be adjusted to that. I don't know how the values are read in the code, but a transformation matrix where either x or y value are negative hints to wrong contour direction while both being negative or positive point to correct contour direction.

`(1, 0, 0, 1, 0, 0)`: normal contour
`(-1, 0, 0, 1, 0, 0)`: reversed contour
`(1, 0, 0, -1, 0, 0)`: reversed contour
`(-1, 0, 0, -1, 0, 0)`: normal contour

**Comment by arrowtype** [comment]
Sorry I didn't see this a lot earlier, but yes, I have found that transformed components tend to fail in most printers, as postscript doesn't handle it well. See https://github.com/arrowtype/recursive/issues/412 for more details.

**Comment by simoncozens** [comment]
Wait, we fixed this!

```
## 0.8.9 (2022-Jun-16)

  - **[com.google.fonts/check/transformed_components]:** Check for any component transformation only if font is hinted, otherwise check only for flipped contour direction (one transformation dimension is flipped while the other isn't)
```
