### ISSUE TITLE
[com.google.fonts/check/glyph_coverage] Kernal should be minimum?

### ISSUE THREAD

**Issue by aaronbell** [fonttools/fontbakery#4111]
## Observed behaviour
My understanding is that the GF Latin Kernal has become the new "standard" for minimum character set, rather than Core. However, the check is still referencing Core.

## Expected behaviour
I'd expect that the check should be referencing the Kernal glyph set instead.

## Resources and exact process needed to replicate

https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin
https://github.com/JAMO-TYPEFACE/Grandiflora/tree/main/Fonts (still updating, but the character set is missing items from Core)

**Comment by RosaWagner** [comment]
You are right regarding the families that you onboard (CJK).
But Latin Core is still the standard minimal glyphset for L-C-G families. In general, it is recommended to always cover Latin_Core, but Kernel may be enough if the primary script of the font is not latin, in particular font with complex shaping. 

I was actually coming here to ask for the same improvement since the FAIL on all JAMO fonts for glyphset coverage should be reduce to make sure that "only" Kernel is covered when a primary script field is specified in METADATA.pb.

For example in this PR: https://github.com/google/fonts/pull/6276 it is hard to see the actual mandatory codepoints. In this PR it was easier to spot: https://github.com/google/fonts/pull/6277

cc @yanone
