### ISSUE TITLE
Do we follow googlefonts.github.io/python recommendations?

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#4246]
I propose to update this repo to conform to https://googlefonts.github.io/python if there are any places it deviates, or, change those recommendations if there are good reasons not to. 

(Tagging as a quick issue to first confirm conformance to that checklist)

**Comment by felipesanches** [comment]
yes, after quickly glancing over the list, I can confirm we follow most of that. We used to use tox, but that was removed recently by @miguelsousa and I decided to do the same because I was also not using it. As https://googlefonts.github.io/python has "TODO" and "Why tox?" when discussing tox, I think it is fine. Maybe it is actually not essential to use it. Or would need stronger explanation of why we should always adopt it.

Also, very recently we started using black.

**Comment by felipesanches** [comment]
> "Fail CI when pytype fails."

That's something we still don't do.

**Comment by felipesanches** [comment]
> "extras_require specifies development-only dependencies under the key called `dev`"

We recently improved a lot the way dependencies are handled and we're using many vendor-specific extras. It would be very simple to add the `dev` one as well. And I'd put "pytest" in it, which would be enough for running code-tests locally during development (which is also why tox was suggested, I guess)

**Comment by moyogo** [comment]
@felipesanches 
> As https://googlefonts.github.io/python has "TODO" and "Why tox?" when discussing tox, I think it is fine. Maybe it is actually not essential to use it. Or would need stronger explanation of why we should always adopt it.

Running tox locally can help cleaning up PR before they are run with CI.

**Comment by felipesanches** [comment]
> Running tox locally can help cleaning up PR before they are run with CI.

I often run `pytest -x tests` locally.

**Comment by moyogo** [comment]
> I often run pytest -x tests locally.

That’s probably good enough for testing before pushing commits.
Tox can be used to run it in different python versions but not on different platforms. So to be thorough running it on CI is better anyway. I’ɗ say it’s fine not to use tox locally.
