### ISSUE TITLE
fontbakery web is incomplete, but that's not immediatly clear to users

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4261]
The checks than can't be run do display a message explaining it. But @vv-monsalve today told me she believes a warning should be displayed in the front page even before any check is run, so that it is clearer to the users that the web version is still experimental and currently incomplete.

**Comment by simoncozens** [comment]
I'm not convinced by this. "Still experimental and currently incomplete" suggests that one day we're going to make a *full* WASM version that does everything the command-line version does. This isn't going to happen, so let's not give people false hope. We already make it clear that some checks don't run, explain why not, and explain that the command-line version is best. I don't think we should do any more than that.

**Comment by vv-monsalve** [comment]
> We already make it clear that some checks don't run, explain why not, and explain that the command-line version is best.

Where have we made it clear for the users? It is not informed on the front page, and it was not informed in the tweet about the WASM version.

**Comment by vv-monsalve** [comment]
> the web version is still experimental and currently incomplete.

Otoh, is how @felipesanches defined the WASM version. And there is when I said that, if that is the case, this should be warned to users.

**Comment by vv-monsalve** [comment]
> @vv-monsalve, as a user who did not at first understand that while using the tool, would you mind sharing your perspective on this?

This is an issue opened by you immediately after a meeting, so it's missing the context, and others discussed there (plus things I didn't mention as the meeting was reaching the end). If you opened the issue, please make it because you consider something a valid inclusion and make it in your own terms. 

Otherwise, if this issue is going to be based on my comment at the meeting, I would prefer it to be closed here (I would do it if I can). I'll open another one providing feedback regarding the UX/UI (as I've done before) but on my own terms.

**Comment by felipesanches** [comment]
ok, thanks, @vv-monsalve

**Comment by felipesanches** [comment]
> If you opened the issue, please make it because you consider something a valid inclusion and make it in your own terms.

yes, I do consider it a valid concern to be addressed. But I respect your wish to open your own issue detailing the problem in your own words.

**Comment by vv-monsalve** [comment]
Thanks, @felipesanches.
