### ISSUE TITLE
[com.google.fonts/check/metadata/valid_name_values] font name field should match nameID16 not 4

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#4262]
(**NOTE:** Please include the check-id in the issue's title. Check-id example: [com.google.fonts/check/metadata/parses])

I don't have permission to the fonttools org so I can't update labels. This is for googlefonts profile, and google fonts priority list and severity 5 cause it's a annoying bug.

## Observed behaviour

Same as in issue https://github.com/fonttools/fontbakery/issues/4086 and that PR https://github.com/fonttools/fontbakery/pull/4120

🔥 FAIL: METADATA.pb font.name field contains font name in right format? ([com.google.fonts/check/metadata/valid_name_values](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/valid_name_values))
🔥 FAIL METADATA.pb font.name field ("Noto Serif TC") does not match correct font name format ("Noto Serif TC ExtraLight"). [code: mismatch]

## Expected behaviour

The check should pass, the font name field is the font family name (name ID16 or 1 when no 16), and therefore should not display nameID17 (style name) or 2 if not 17.

## Resources and steps needed to reproduce

Seen in https://github.com/google/fonts/pull/6695#issuecomment-1719506323

**Comment by RosaWagner** [comment]
@felipesanches can you add the label "GF priority list" ?

**Comment by simoncozens** [comment]
I'm a bit confused about this.

In the case of Noto Serif TC, "font family name" (name ID 1) was 'Noto Serif TC ExtraLight' and "typographic family name" (name ID 16) was 'Noto Serif TC'. Fontbakery only looks at these two names; it does not look at ID 17 or 4.

I think the problem is here:

```
    if style in RIBBI_STYLE_NAMES:
        familynames = font_familynames
    else:
        familynames = typographic_familynames
```

"style" returns "Regular" if the default wght coordinate != 700. In this case, the default weight coordinate is 200, so it's considered "Regular". This is obviously wrong but it's a leftover from the old RIBBI world. Anyway, it returns Regular, which is a RIBBI name, so we check the font family name ("Noto Serif TC ExtraLight") against the name in METADATA ("Noto Serif TC") and the check fails. (Then I changed the METADATA name to "Noto Serif TC ExtraLight", and it passed.)

I don't know what the solution is, but fontbakery was *not* looking at ID 17 at all.

@RosaWagner, are you saying it should look at 16 if 16 exists, then look at 1 if not? i.e. replace the above with

```
     familynames = typographic_familynames or font_familynames
```

(Also we should fix `style` because it's clearly out of date.)

**Comment by RosaWagner** [comment]
I don't know how the check works exactly, but yes this is my proposal; nameID16 usually only gives the family name, which is not the case of nameID1 for non-RIBBI styles which have the style name into the nameID1. So nameID16 should be the first to look at, and if it doesn't exist, it means the font is RIBBI and so nameID1 should display the family name only. And I added as a precaution, nameID17 or 2 should not be in the `font name` field of METADATA.pb.

**Comment by felipesanches** [comment]
thanks, @m4rc1e
