### ISSUE TITLE
[setup.py] Always specify latest available gflanguages, glyphsets and shaperglot

### ISSUE THREAD

**Issue by yanone** [fonttools/fontbakery#4351]
**NOTE:** The original title of this issue was: **"[shape_languages] Automatically update dependencies"**

----
Now that the `shape_languages` check is complete (https://github.com/fonttools/fontbakery/pull/4350), we need a way to automatically update package versions in Fontbakery of the following 3 packages:

* `glyphsets`
* `shaperglot`
* `gflanguages` (not yet linked in Fontbakery directly, but I would link it explicitly because `shaperglot` uses `gflanguages` and if we link it explicitly, we don't need to wait for a `shaperglot` update in order to use the latest `gflanguages`

**Comment by yanone** [comment]
It's not about fontbakery releases. I want the dependencies to become available through fontbakery almost instantly as soon as they are released. As an onboarder, I don't use fontbakery releases, but always use the bleeding-edge repository version. I update it daily before I start working on fonts. 

If dependencies are updated almost instantly, I receive up-to-date dependencies at least daily.
I really think this should be automated for select packages.

**Comment by yanone** [comment]
Also, shouldn't the dependencies be updated in setup.py for releases?

**Comment by yanone** [comment]
> If you already have fontbakery installed, then the dependencies will not be updated, unless we edit setup.py.

Just to clarify: Does this mean that dependencies aren't getting updated when an existing fontbakery installation gets updated?

**Comment by yanone** [comment]
That's even worse than I thought. It's absolutely critical that these select few dependencies get updated every time someone updates their existing fontbakery installation. The correct function of fontbakery literally depends on the dependencies being up-to-date.

I as an engineer can update the packages manually locally. But no user shall required to know that they need to update a certain bunch of dependencies manually alongside updating fontbakery itself.

I need to reiterate that it's critical that dependencies for gflanguages, shaperglot and glyphsets get updated automatically in setup.py as soon as they are published, or soon after; at least daily.

Please re-open this issue.

**Comment by felipesanches** [comment]
setup.py specify the minimum version of dependencies.

When a user installs a program from scratch using pip, it will use the instructions from setup.py to determine which dependencies are needed, then it downloads and install them all. Since it is a fresh new install, it will simply install whatever latest version of all dependencies is available at the moment.

If the user installs another program (or a new version of the same program), then the repository of packages will be queried again always trying to comply with the rules specified in setup.py.

So, even if a newer version of a dependency is available, it is not necessary to update it because something already installed is enough to satisfy setup.py. We will only change setup.py when a program starts using some new API and then it becomes mandatory to use a newer version of the dependency. And pip will understand that and will install the newer version of the dependency in that case.

**Comment by yanone** [comment]
The priority should be exactly the other way around. The dependencies need to be up-to-date in setup.py, not in requirements.txt which is only used for development. That's exactly where, as a developer, I can take care of updating packages myself if something's out of date.

**Comment by felipesanches** [comment]
my last post here was written before reading your last messages. I'll read them now and possibly reply with more comments, please wait.

**Comment by yanone** [comment]
And **shaperglot**. These three hold _data_ about languages that changes, not just code, and the data needs to be up-to-date always.

**Comment by felipesanches** [comment]
oh, yes, that's right!

**Comment by yanone** [comment]
Yes, there may be more packages that need to be updated automatically for the user. I'm not sure which all they are. Basically all packages that hold data. **axisregistry** is certainly one of them.
