### ISSUE TITLE
Check ID: com.google.fonts/check/font_copyright should accept date ranges

### ISSUE THREAD

**Issue by tphinney** [fonttools/fontbakery#4386]
com.google.fonts/check/font_copyright

ScienceGothic[YOPQ,slnt,wdth,wght].ttf
FAIL :
Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)" But instead we have got: "Copyright 2019-2022 The Science Gothic Project Authors. https://github.com/tphinney/science-gothic/blob/main/AUTHORS.txt" [code: bad-notice-format]

## Observed behaviour

Fontbakery is rejecting a date range.

## Expected behaviour

Date ranges are completely standard and expected in copyright notices. Fontbakery should accept ANY list of one or more years, one or more ranges of years, or a mix of the two. For example, this should be accepted:

Copyright 2012-2014, 2016, 2019-2021, 2023 The Science Gothic Project Authors. https://github.com/tphinney/science-gothic/blob/main/AUTHORS.txt

## Resources and steps needed to reproduce

[fonts/variable/ScienceGothic[YOPQ,slnt,wdth,wght].ttf](https://github.com/googlefonts/science-gothic/blob/main/fonts/variable/ScienceGothic%5BYOPQ%2Cslnt%2Cwdth%2Cwght%5D.ttf)

Fontbakery.com does not list a version in its report. :(  So, whatever version was current on 10 Dec 2023 at 11:46 am Pacific time.

**Comment by davelab6** [comment]
I think we should update the check so that `Copyright 2012 The Science Gothic Project Authors` is a pass, `Copyright 2012-2014, 2016, 2019-2021, 2023 The Science Gothic Project Authors` is a warn, and `Copyright yo!` is a fail. 

Here is a regex for what I mean from a gpt:

    Copyright (?:\d{4}(?:-\d{4})?(?:,\s*\d{4}(?:-\d{4})?)*)+ The Science Gothic Project Authors

"
Explanation:

* Copyright: Matches the literal string "Copyright".
* `(?:\d{4}(?:-\d{4})?(?:,\s*\d{4}(?:-\d{4})?)*)+`: Matches one or more occurrences of a year or a year range separated by commas.
* `\d{4}`: Matches any four-digit number (year).
* `(?:-\d{4})?`: Optionally matches a hyphen followed by another four-digit number (for year ranges).
* `(?:,\s*\d{4}(?:-\d{4})?)*`: Matches zero or more occurrences of a comma followed by whitespace, another year or year range, and so on.
* `The Science Gothic Project Authors`: Matches the literal string "The Science Gothic Project Authors".

This regex will match the entire copyright string, including any number of comma-separated year ranges.

Here are some additional notes:

* This regex assumes that the years are always in ascending order within a range.
* This regex does not handle potential errors in the copyright string, such as invalid year formats or typos.

"

**Comment by tphinney** [comment]
I could live with that.

**Comment by felipesanches** [comment]
> Copyright 2012-2014, 2016, 2019-2021, 2023 The Science Gothic Project Authors is a warn

Why a WARN here? I'll make it a PASS as well. I don't see any problem with that, other than being just a bit too verbose.
