### ISSUE TITLE
[com.google.fonts/check/family/equal_unicode_encodings] Why?

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4569]
I've been trying to write a rationale for this check, but I can't think of one. Why does it matter whether or not all format 4 cmap tables in a family have the same Unicode encoding? Is there any software which doesn't deal with this case?

Should we deprecate this check?

As a meta-question, we have a "proposal" for this check: `legacy:check/013`. Is there anywhere I can look up some discussion about why "check 013" was proposed? If not, all it tells me is "We have this check now because we had it at some point in the past", which is not useful information.

**Comment by khaledhosny** [comment]
For fun, I tried to git blame this, after a web of renames, splitting, consolidating, splitting, consolidating, splitting, I traced it back to this commit https://github.com/fonttools/fontbakery/commit/f2296c562fa2ff5d639f84eb76593babacc1db51, which supposedly copies the code with no git history from a now non-existing fontbakery-cli repository.

Fortunately some kind soul forked this fontbakery-cli repository at some point and preserved a little bit of it for future software archaeologists, so I tried to git blame it there, but it was introduced in mass commit with the dreaded "[Initial commit](https://github.com/lowks/fontbakery-cli/blame/514cc010c1118bbcef078aeb64a87add05322c4a/bakery_lint/tests/downstream/test_check_glyph_consistency.py#L58)" message, with no history at all.

**Comment by khaledhosny** [comment]
OK, doing a plain git log to not get over moving stuff to a separate repo and back, this is now finally traced back to ba1671e5b3875c8e2c2ec92d3b5b95ed2c44d2c3 and #234. Though the test morphed somehow and instead of checking that glyphs are mapped to the same code points across family, it is now doing a useless check for platform encoding ID.

**Comment by moyogo** [comment]
@simoncozens @khaledhosny what's the use case for not having the same characters in the fonts of a family?

**Comment by khaledhosny** [comment]
> @simoncozens @khaledhosny what's the use case for not having the same characters in the fonts of a family?

Some applications fail to do fallback if characters are covered by, say, regular style but not italic styles. Many fonts have Arabic glyphs in regular and bold, but not italic and bold italic and I have seen applications showing .notdef for Arabic glyphs when applying italic style to such fonts (instead of the expected auto slanting, or even falling back to a d different font). It is a rare issue, but I can see why someone would want to check for it, but the current check is not even doing this and is essentially of no value.

**Comment by moyogo** [comment]
Oh, looked at the check. It's checking the first cmap table with format 4 has the same platform encoding in all fonts of a family.

There's a rationale for checking the fonts of a family are consistent, but this is weird.

**Comment by simoncozens** [comment]
We *also* have a check for same codepoints across a family. This one is just weird. Let's kill it!

**Comment by moyogo** [comment]
@khaledhosny yes, I misunderstood what this issue and check was about. The com_google_fonts_check_family_equal_codepoint_coverage check ensures codepoints coverage is consistent as @simoncozens says.

I guess this check could be dropped.

One thing about com_google_fonts_check_family_equal_codepoint_coverage is that it uses font_codepoints (itself just ttFont.getBestCmap) so only one cmap subtable is checked there as well. Probably not a big problem but some families with inconsistent cmap subtables codepoints coverage may still get a PASS if the best cmap subtables are consistent.
