### ISSUE TITLE
[com.google.fonts/check/glyphsets/shape_languages]: Output is too long

### ISSUE THREAD

**Issue by m4rc1e** [fonttools/fontbakery#4781]
![scroller](https://github.com/fonttools/fontbakery/assets/7525512/ade9c5cd-d07b-48be-928b-3b8609ae4860)

This check has made the report for Montserrat 20x+ longer.

**Comment by m4rc1e** [comment]
@felipesanches Possible to look into this since it makes reports a complete mess. You can use Merriweather as a reference, https://github.com/ebensorkin/Merriweather4

**Comment by felipesanches** [comment]
@m4rc1e, I'm having some trouble when trying to build the fonts from that Merriweather4 repo:

![Screenshot from 2024-09-18 02-38-44](https://github.com/user-attachments/assets/896b2ed1-1ed1-404d-93d4-1f5e52ab0c0e)


Can you help me troubleshoot that? Or, alternatively, can you provide me some sample prebuilt font binaries?

**Comment by felipesanches** [comment]
thanks!

**Comment by felipesanches** [comment]
The culprit here seems to be the message `"The locl feature did not affect Eng"`, where 'Eng' is "(capital: Ŋ, lowercase: ŋ) a letter of the Latin alphabet, used to represent a voiced velar nasal (as in English singing) in the written form of some languages and in the International Phonetic Alphabet."

I wouldn't like to add such a specific hardcoded filtering to omit this message. We should verify whether the shaperglot message complaining about the Eng glyph is bogus or actually valid.

If filtering is needed, then I'd suggest adding to the output some message such as: "The shaperglot failures listed below happened too often: <and a bullet list of them all de-duplicated to keep the list short>"

**Comment by m4rc1e** [comment]
> If filtering is needed, then I'd suggest adding to the output some message such as: "The shaperglot failures listed below happened too often: <and a bullet list of them all de-duplicated to keep the list short>"

Sounds good to me. What we currently have is a fail for each language, why can't we just group all the langs together where this eng glyph is an issue. It would make the report much more concise.
