### ISSUE TITLE
[gdef_spacing_marks] Reported "spacing marks" *are* non-spacing

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4824]
## Observed behaviour

```
    WARN The following spacing glyphs may be in the GDEF mark glyph class by mistake:
         Uml.Acute (U+0301), Uml.Diaeresis (U+0308), Uml.DotAbove (U+0307),
         Uml.Double.Macron (U+035E), Uml.Grave (U+0300), Uml.InvBreve (U+0311),
         Uml.Macron (U+0304), Uml.Overline (U+0305) and u323 (U+0323) [code:
         spacing-mark-glyphs]
```
## Expected behaviour

U+0301 is COMBINING ACUTE ACCENT, U+0308 is COMBINING DIAERESIS, etc. These are all non-spacing Unicode characters in the "Combining Marks" block, and should be considered non-spacing.

## Resources and steps needed to reproduce

Seeing it in https://github.com/notofonts/todhri

**Comment by felipesanches** [comment]
Here's how the check decides which glyphs to report as being "spacing glyphs":

```python
spacing_glyphnames = {
            name for (name, (width, lsb)) in ttFont["hmtx"].metrics.items() if width > 0
}
```


So, I think it is only a matter of improving the log-message.

I've just changed it to: `f"The following glyphs seem to be spacing (because they have width > 0 on the hmtx table) so they may be in the GDEF mark glyph class by mistake, or they should have zero width instead:\n {formatted_list}"`
