### ISSUE TITLE
[googlefonts/article/images] detect relative image paths are valid

### ISSUE THREAD

**Issue by vv-monsalve** [fonttools/fontbakery#4848]
## Observed behavior

A PR failed to be pushed due to the presence of invalid relative image paths, causing a break in the Dev server.

## Expected behavior

The check should detect if these paths are present in the metadata file.

Log level result:  ☠️ Fatal

## Resources and steps needed to reproduce

[Original PR](https://github.com/google/fonts/pull/8208) introducing the situation
[PR to solve the situation](https://github.com/google/fonts/pull/8253), made by Rod.

**Comment by felipesanches** [comment]
I see that the check reported the missing file at https://github.com/google/fonts/pull/8208#issuecomment-2376948957
So it is just a matter of making that a **FATAL** message instead of mere **WARN**. 

![Screenshot from 2024-10-10 12-02-54](https://github.com/user-attachments/assets/5327f627-3fff-46c8-9ca3-f1cfd160d52e)

**Comment by vv-monsalve** [comment]
> Visual asset files are missing:

The message didn't help to identify the situation since the files were not missing but had an invalid path.  
The message could be more accurate in cases like this.
